README.rst
src/argus_htmx/context_processors.py
src/argus_htmx/static/color-schemes/blue.css
src/argus_htmx/static/color-schemes/dark.css
src/argus_htmx/static/color-schemes/light.css
src/argus_htmx/templates/htmx/base.html
src/argus_htmx/views.py

Depends on Uninett/Argus#810
Use a context processor to set the variable "theme" in all contexts. The variable corresponds to a file in `static/color-schemes/`.
Included themes: dark, light, blue, where dark supports darkmode and light is the default.
How to use: add one of the included context processors either depending on #810 or manually.
Testing with GET: use the "argus_htmx.context_processors.theme_via_GET" context processor and suffix `?theme=SOMECOLOR` to any url.
Testing with session: use the "argus_htmx.context_processors.theme_via_session" context processor and set the correct key in your session like so: `request.session["theme"] = "SOMECOLOR"`

Add theming-support

---

runtests.py
tests/settings.py
tests/urls.py
tox.ini

This setup will work if *not* testing anything that uses imports from argus-server. If importing anything from argus-server it becomes necessary to expand the settings-file and switch to an actual postgres as the test database.

Setup testing with tox

---

pyproject.toml
src/argus_htmx/middleware.py
tests/test_middleware.py

For this to work, change the following settings:
```
LOGIN_URL = "/accounts/login"
PUBLIC_URLS = [
"/accounts/login",
"/api",
]
MIDDLEWARE += ["argus_htmx.middleware.LoginRequiredMiddleware"]
```
Urls in `PUBLIC_URLS` are ignored by the middleware. Likewise, if the view has the attribute `login_required` set to "False", this middleware is skipped. If neither holds an unauthenticated user is redirected to LOGIN_URL.
(argus-server needs to mark "/" as "login_required = False" and any public urls not in the API.)

Add middleware for forcing logins, w/tests

---

src/argus_htmx/templates/htmx/incidents/_incident_filterbox.html

Adding the border class makes input field respect default border width

Fix filterbox text input border

---

README.rst
src/argus_htmx/templates/htmx/incidents/incident_list.html

Supports adding a widget to the incident listing through settting the `incidents_extra_widget` context variable to a template path that will then be included next to the menu bar. The widget will take up 1/3 of the width.

Support extra widget through context processor

---

src/argus_htmx/templates/htmx/incidents/incident_detail.html

Show full event type name in incident detail

---

src/argus_htmx/incidents/forms.py
src/argus_htmx/incidents/urls.py
src/argus_htmx/incidents/views.py
src/argus_htmx/templates/htmx/incidents/_incident_ticket_edit_modal.html
src/argus_htmx/templates/htmx/incidents/_incident_ticket_manual_create_modal.html
src/argus_htmx/templates/htmx/incidents/incident_detail.html

Closes #124 as well, at least on Firefox.
This does not handle autocreation of tickets. 
We must settle on how to report the many possible errors from the ticket plugin before we can support autocreation of tickets.

Make modal for add/edit ticket url work in details view

---

src/argus_htmx/templates/htmx/incidents/incident_detail.html

Closes #128. 
Open for discussion about which of the commits to merge - in the first two commits I made it look like the original Argus-frontend and in the third I added that clicking the link will open it in another tab.

Show "Ticket" instead of "Acknowledged" in status block of details page

---

src/argus_htmx/context_processors.py
src/argus_htmx/dateformat/constants.py
src/argus_htmx/dateformat/urls.py
src/argus_htmx/dateformat/views.py
src/argus_htmx/templates/htmx/base.html
src/argus_htmx/templates/htmx/dateformat/_dateformat_dropdown.html
src/argus_htmx/templates/htmx/dateformat/_dateformat_list.html
src/argus_htmx/templates/htmx/incidents/_incident_start_time.html
src/argus_htmx/templates/htmx/incidents/_incidents_refresh_info.html
src/argus_htmx/templates/htmx/incidents/incident_detail.html
src/argus_htmx/urls.py

Closes #100
This is based very closely on the theme-switching UX.
Set up: add "argus_htmx.context_processors.datetime_format_via_session" to the context_processors" in the TEMPLATES-setting in your localsettings-file, or change the argus_htmx-entry in EXTRA_APPS to:
```
{
"app_name": "argus_htmx",
"urls": {
"path": "",
"urlpatterns_module": "argus_htmx.urls"
},
"context_processors": [
"argus_htmx.context_processors.theme_via_session",
"argus_htmx.context_processors.datetime_format_via_session"
],
"middleware": {
"argus_htmx.middleware.LoginRequiredMiddleware": "end"
}
},
```
One difference from the themes: in order to actually switch to the new format, the page is always refreshed. There might be redundant htmx-code for that reason.
There's a new optional setting …

Add dropdown for user to choose datetime format

---

src/argus_htmx/context_processors.py

Currently DATETIME_DEFAULT is not considered for new django sessions (if `datetime_format_name` is not in the session) but the default datetime format is hardcoded to `LOCALE`, limiting the usefulness of `ARGUS_FRONTEND_DATETIME_FORMAT`
this fixes that

Pick DATETIME_DEFAULT for empty sessions

---

README.rst
src/argus_htmx/incidents/views.py
src/argus_htmx/templates/htmx/incidents/_incident_filterbox.html
src/argus_htmx/templates/htmx/incidents/_incident_table.html
src/argus_htmx/templates/htmx/incidents/_incidents_refresh_info.html

Closes #76
Add a select element for choosing the page size (max number of incident rows shown in the table). The default page size is 10 and selectable page sizes are [10, 20, 50, 100]. It is possible to override these numbers by setting the ``ARGUS_INCIDENTS_DEFAULT_PAGE_SIZE`` and ``ARGUS_INCIDENTS_PAGE_SIZES`` setting
respectively.
some noteworthy things
* hitting enter on a filterbox fields would trigger a page reload (something djang-forms maybe?). it was necessary to intercept the enter event in order to include the page_size form value, otherwise it would only send in the filter box params
* I wrapped the whole refresh-info stats element in a form, because I think we also want to make the auto-refresh frequency selectable
This PR is still a wip because I'm not quite happy with the …

Selectable incident list page size

---

src/argus_htmx/templates/htmx/incidents/_incidents_update_menu.html

Closes #152, #154
The problem was due to conflicting grid layout styles between `<dialog>` (the modal box) and `.menu li` (listitem tags that modals were wrapped with).
There are alternative solutions to the one in this PR:
- break the overlap between the conflicting styles by adding another tag (layer) between listitem and modal. Achievable by adding a wrap `<div class="contents">...</div>` around modal (either directly in base template `_base_form_modal.html`, or around each `include` in `_incidents_update_menu.html`). Docs about display option contents: https://tailwindcss.com/docs/display#contents. Pros: Very strong alternative, plus it could somewhat be a failsafe against future broken placements of modals. Cons: Adds "empty" layer of nesting, aka adding structural tag purely for …

Fix broken layout of bulk modals

---

README.rst

Without this context processor the incident page fails with "VariableDoesNotExist at /incidents/"

Add datetime format processor to setup examples in README

---

.github/workflows/lint.yml
.pre-commit-config.yaml
pyproject.toml

Dependent on #175.
`changed-files` needs to be included when the PR has been approved.

Add critical linting using ruff

---

src/argus_htmx/templates/htmx/incidents/incident_detail.html

This is to follow rule T001 of djLint.
Reference: https://www.djlint.com/docs/linter/#rules

Add whitespace after variable in template

---

src/argus_htmx/templates/htmx/incidents/_incident_table.html

This is to follow rule H026 of djLint.
Reference: https://www.djlint.com/docs/linter/#rules

Remove empty class tag

---

src/argus_htmx/templates/htmx/base.html
src/argus_htmx/templates/htmx_base.html

Dependent on #199. 
This is to follow rule T003 of djLint.
Reference: https://www.djlint.com/docs/linter/#rules

Add names to endblocks

---

.github/workflows/format.yml
.pre-commit-config.yaml
pyproject.toml

This adds formatting HTML with djLint to pre-commit and Github actions. 
#182 actually formats the code.

Add djLint to format HTML

---

pyproject.toml

They are already fulfilled on the current codebase. 
Tagging as discussion to invite discussion if/which of these rules we want.
Reference: https://docs.astral.sh/ruff/rules/#pyflakes-f

Add F5, F6, F8 and F9 rules to ruff

---

pyproject.toml

Codebase already fulfills these rules. 
Tagging as discussion to invite discussion if/which of these rules we want.
Reference: https://docs.astral.sh/ruff/rules/#error-e

Add E4 rules to ruff

---

README.rst
pyproject.toml
src/argus_htmx/auth/views.py
src/argus_htmx/templates/registration/login.html
src/argus_htmx/urls.py

See https://indieweb.org/NASCAR_problem
In order to properly test this you need one or more python social auth provider backends added to `AUTHENTICATION_BACKENDS` and the necessary KEY and SECRET set up in settings.
See argus-server docs for more info.

Add support for a menu of SSO login options

---

src/argus_htmx/templates/htmx/base.html
src/argus_htmx/templates/htmx/user/settings.html
src/argus_htmx/urls.py
src/argus_htmx/user/__init__.py
src/argus_htmx/user/urls.py
src/argus_htmx/user/views.py

Butt-ugly first draft of a user settings page, more or less based on the current user drop-down menu.
I'm going to need some styling help here, because Tailwind is just confusing and downright counter-intuitive to an old-timer like me ;)
Closes #170

Implement a simple user settings page

---

pyproject.toml

Rule D018: `(Django) Internal links should use the {% url ... %} pattern.` (https://www.djlint.com/docs/linter/#rules) 
This was only temporarily introduced until #186 could be merged

Remove D018 (urlpatterns format) from ignored linter rules

---

.github/workflows/lint.yml
pyproject.toml

We are using the default rules by now (see: https://docs.astral.sh/ruff/configuration/ and https://docs.astral.sh/ruff/rules/)
Also renames the Python linting workflow to not mention `critical` anymore since we're now linting for more than just critical rules.

Remove selected rules from ruff config

---

src/argus_htmx/themes/views.py

a regression in https://github.com/Uninett/argus-htmx-frontend/pull/212/ caused the change theme view to return an incorrect resopnse  which broke subsequent theme changes 
see https://github.com/Uninett/argus-htmx-frontend/pull/212/files#diff-01ed40f6dbfb6d8070dccb23a1c34c1d819fb9175eace41c7cd175f64b0d10fcR47

Fix regression in htmx response to theme update
