Uninett/argus-htmx-frontend

- README.rst
> Improve tailwind install/usage docs slightly

- README.rst
> Small fixes in TW CSS docs

- src/argus_htmx/static/logo_white.svg
- src/argus_htmx/templates/htmx/base.html
> Add logo to navbar

- src/argus_htmx/static/styles.css
- src/argus_htmx/templates/htmx/base.html
Closes #57
New menu looks like this when expanded:
> Convert user section in navbar to an avatar with dropdown menu

- README.rst
Found several issues as I tried to follow README.md step by step.  See individual commits for comments
> Fix issues with getting started-examples in README.md

- src/argus_htmx/static/styles.css
- src/argus_htmx/templates/htmx/_base_form_modal.html
- src/argus_htmx/templates/htmx/incidents/_incident_acknowledge_modal.html
- src/argus_htmx/templates/htmx/incidents/_incident_close_modal.html
- src/argus_htmx/templates/htmx/incidents/_incident_ticket_autocreate_modal.html
- src/argus_htmx/templates/htmx/incidents/_incident_ticket_edit_modal.html
- src/argus_htmx/templates/htmx/incidents/incident_detail.html
This shows everything in the details page that argus classic does, though with no buttons working.
> Improve classic details page

- src/argus_htmx/static/styles.css
- src/argus_htmx/templates/htmx/_base_form_modal.html
~Depends on #82 (not technically but for being able to test that refactor doesn't break functionality)~
> Use dialog tag for modals

- src/argus_htmx/static/styles.css
- src/argus_htmx/templates/htmx/_base_form_modal.html
- src/argus_htmx/templates/htmx/incidents/_incident_acknowledge_modal.html
> Polish base modals and ack input fields

- src/argus_htmx/static/styles.css
- src/argus_htmx/templates/htmx/base.html
- src/argus_htmx/templates/htmx/themes/theme_dropdown.html
- src/argus_htmx/templates/htmx/themes/theme_list.html
- src/argus_htmx/themes/urls.py
- src/argus_htmx/themes/views.py
Closes #75 
Do we need to keep the old theme page?
> Make theme selectable via dropdown in user menu

- src/argus_htmx/incidents/forms.py
- src/argus_htmx/incidents/urls.py
- src/argus_htmx/incidents/views.py
- src/argus_htmx/static/styles.css
- src/argus_htmx/templates/htmx/incidents/_incident_close_modal.html
- src/argus_htmx/templates/htmx/incidents/_incident_reopen_modal.html
- src/argus_htmx/templates/htmx/incidents/incident_detail.html
I'm not sure whether the message should be required or not. It is not required in the data model.
> Make close/reopen buttons work in details page

- src/argus_htmx/templates/htmx/incidents/_incident_source.html
> Hide source type in source column in incident list

- src/argus_htmx/settings.py
> Hide actions column

- src/argus_htmx/incidents/customization.py
- src/argus_htmx/settings.py
- src/argus_htmx/templates/htmx/incidents/_incident_combined_status.html
> Show open and acked together as in classic

- src/argus_htmx/templates/htmx/incidents/_incident_ack.html
- src/argus_htmx/templates/htmx/incidents/_incident_status.html
> Style status and ack columns

- src/argus_htmx/incidents/customization.py
- src/argus_htmx/settings.py
- src/argus_htmx/static/styles.css
- src/argus_htmx/templates/htmx/incidents/_incident_ticket.html
> Make a column for tickets

- src/argus_htmx/static/styles.css
- src/argus_htmx/templates/htmx/incidents/_incident_level.html
- src/argus_htmx/templatetags/argus_htmx.py
Closes #116
We need 5 different color props for the badges...
I have added a header with a fixed width (min-w-32) to prevent overflow when resizing the window. It might be better to set the text as nowrap and then fit to content or min-width.
> Prettyprint level

- src/argus_htmx/templates/htmx/incidents/_incident_table_rows.html
> Show different "no hits" text for empty db

- .github/workflows/format.yml
- .gitignore
The `changed_files` needs to be applied, but I first want to show that it is also working on the whole codebase.
> Add workflow to check formatting using ruff

- src/argus_htmx/templates/registration/login.html
This is to follow rule H025 of djLint.
Reference: https://www.djlint.com/docs/linter/#rules
> Add closing to div in login template

- pyproject.toml
- tests/test_middleware.py
To add E7 rules to ruff.
Tagging as discussion to invite discussion if/which of these rules we want.
Reference: https://docs.astral.sh/ruff/rules/#error-e
> Rewrite assigned lambda expressions as def

- pyproject.toml
- src/argus_htmx/admin.py
- src/argus_htmx/incidents/urls.py
- src/argus_htmx/incidents/views.py
- src/argus_htmx/models.py
- src/argus_htmx/tests.py
- src/argus_htmx/themes/utils.py
- src/argus_htmx/themes/views.py
To add F4 rules to ruff. 
Tagging as discussion to invite discussion if/which of these rules we want. 
Reference: https://docs.astral.sh/ruff/rules/#pyflakes-f
Also removes a dependency that had become unused.
> Remove unused imports in Python code and unused dependency

- src/argus_htmx/templates/htmx/incidents/_base_incident_update_modal.html
Another complaint of djLint (T002)
> Use double quotes in tags

- README.rst
> Update README with new "How to play"-instructions

- .pre-commit-config.yaml
This version promises to have big formatting performance improvements. 
Reference: https://github.com/djlint/djLint/releases/tag/v1.35.4
> Upgrade djLint version to 1.35.4

- .pre-commit-config.yaml
> Upgrade ruff in pre-commit to 0.7.2

- src/argus_htmx/user/preferences/models.py
following https://github.com/Uninett/Argus/pull/938
> Use @preferences decorator instead of directly inheriting from Preferences
